development:
  adapter: postgresql
  encoding: unicode
  database: tamojunto_development
  pool: 5
  #username: postgres
  #password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tamojunto_test
  pool: 5
  username: postgres
  password: password
  min_messages: WARNING
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: tamojunto_production
  pool: 5
  username: postgres
  password:
  host: localhost
